force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Unit_Score__c.field-meta.xml
<CustomField>
    <fullName>Unit_Score__c</fullName>
    <label>Unit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <displayFormat>UR-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Number_Tries__c.field-meta.xml
<CustomField>
    <fullName>Number_Tries__c</fullName>
    <label>Number Tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Stage_Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Stage_Unit_Response__c</fullName>
    <label>Stage Unit Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <formula>CASESAFEID(Module_Response__r.User__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UserID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Accumulated_Score__c.field-meta.xml
<CustomField>
    <fullName>Accumulated_Score__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Accumulated Score</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitResponseTrigger.cls
public with sharing class UnitResponseTrigger {
    public static void onBeforeUpdate(List<Unit_Response__c> unitRespList, Map<Id, Unit_Response__c> oldUnitRespMap){
        List<Unit_Response__c> answeredUnitResp = new List<Unit_Response__c>();

        for(Unit_Response__c unitRes :unitRespList){
            if(unitRes.Stage_Unit_Response__c == 'Answered' && oldUnitRespMap.get(unitRes.Id).Stage_Unit_Response__c == 'Draft'){
                answeredUnitResp.add(unitRes);
            }
        }

        Map<Id,Unit_Response__c> unitRespWithQuestionRespFromDB = new Map<Id,Unit_Response__c> ([SELECT Id, (SELECT Id, Option__r.Is_Correct__c FROM Question_Responses__r) FROM Unit_Response__c WHERE Id IN :answeredUnitResp]);


        for (Unit_Response__c unitResp : answeredUnitResp) {
            unitResp.Status__c = 'Completed';
            unitResp.Stage_Unit_Response__c = 'Success';
            for(Question_Response__c questionResp : unitRespWithQuestionRespFromDB.get(unitResp.Id).Question_Responses__r) {
                if(!questionResp.Option__r.Is_Correct__c){
                    unitResp.Status__c = 'In Progress';
                    unitResp.Stage_Unit_Response__c = 'Fail';
                    break;               
                }
            }

            if(unitResp.Status__c == 'Completed'){
                if(unitResp.Number_Tries__c == 1){
                    unitResp.Score__c = unitRespWithQuestionRespFromDB.get(unitResp.Id).Unit__r.Unit_Score__c;
                } else if(unitResp.Number_Tries__c == 2){
                    unitResp.Score__c = unitRespWithQuestionRespFromDB.get(unitResp.Id).Unit__r.Unit_Score__c / 2;
                }else {
                    unitResp.Score__c = unitRespWithQuestionRespFromDB.get(unitResp.Id).Unit__r.Unit_Score__c / 4;
                }
            }
        }
    }

    public static void onAfterUpdate(List<Unit_Response__c> unitRespList, Map<Id, Unit_Response__c> oldUnitRespMap){
        List<Unit_Response__c> completedUnitRespList = new List<Unit_Response__c>();
        
        for(Unit_Response__c unitResp : unitRespList){
            if(unitResp.Status__c == 'Completed' && oldUnitRespMap.get(unitResp.Id).Status__c != 'Completed'){
                completedUnitRespList.add(unitResp);
            }   
        }

        Set<Id> usersIds = new Set<Id>();

        for (Unit_Response__c completedUR : completedUnitRespList) {
            usersIds.add(completedUR.UserID__c);
        }

        Map<Id,User> usersMap = new Map<Id,User> ([SELECT Id, Accumulated_Score__c FROM User WHERE Id IN :usersIds]);

        for (Unit_Response__c unitResp : completedUnitRespList) {
            usersMap.get(unitResp.UserID__c).Accumulated_Score__c += unitResp.Score__c;
        }
        update usersMap.values();
    }
}