force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Module Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Module Responses</relationshipLabel>
    <relationshipName>Module_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Module_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Response__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Question Responses</relationshipLabel>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <displayFormat>UR-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Module_Response__c.field-meta.xml
<CustomField>
    <fullName>Module_Response__c</fullName>
    <label>Module Response</label>
    <referenceTo>Module_Response__c</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Number_Tries__c.field-meta.xml
<CustomField>
    <fullName>Number_Tries__c</fullName>
    <label>Number Tries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Stage_Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Stage_Unit_Response__c</fullName>
    <label>Stage Unit Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Responses</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public with sharing class UnitService {
    public class CustomException extends Exception{}
    
    public static Boolean registerUnitResponse (Id unitId, String jsonAnswer){

            Savepoint sp = Database.setSavepoint();

        try{
            //Select Unit From DB
            Unit__c unit = [SELECT Module__c, (SELECT Id FROM Questions__r), (SELECT Id, Number_Tries__c FROM Unit_Responses__r WHERE Module_Response__r.User__c =: UserInfo.getUserId() ORDER BY Number_Tries__c DESC LIMIT 1) FROM Unit__c WHERE Id =: unitId];

            //Check If Module Resp Exist
            Module_Response__c moduleResp = [SELECT Id FROM Module_Response__c WHERE Module__c =: unit.Module__c AND User__c =: Userinfo.getUserId() AND Status__c = 'In Progress'];
            
            //If not exist, I create it
            if(moduleResp == null){
                moduleResp = new Module_Response__c(User__c = Userinfo.getUserId(), Module__c = unit.Module__c, Status__c = 'In Progress');
                insert moduleResp;      
            }          

            //Create & Insert a Unit Response
            Unit_Response__c unitResp = new Unit_Response__c(Unit__c = unitId, Module_Response__c = moduleResp.Id, Stage_Unit_Response__c = 'Draft');
           
            //Add number of tries
            unitResp.Number_Tries__c = !unit.Unit_Responses__r.isEmpty() ? unit.Unit_Responses__r[0].Number_Tries__c + 1 : 1;
            insert unitResp;

            //Create & Insert a Questions Response
            Map<Id,Id> answerMap = (Map<Id,Id>)JSON.deserializeStrict(jsonAnswer, Map<Id,Id>.class);

            List<Question_Response__c> questionRespList = new List<Question_Response__c>();

            for(Question__c question : unit.Questions__r){
                if(answerMap.containsKey(question.Id)){
                questionRespList.add(new Question_Response__c(Question__c = question.Id, Unit_Response__c = unitResp.Id, Option__c = answerMap.get(question.Id)));
                }else{
                    throw new CustomException('La pregunta'
                    + question.Name + 'no fue respondida y es requerida!');
                }
            
            }
            
            insert questionRespList;
        
            //Update Unit Response with a stage 'Answered' to shoot the Trigger

            unitResp.Stage_Unit_Response__c = 'Answered';
            
            update unitResp;
            
            //ES NECESARIA LA QUERY?? O PODRIMOS SOLO RETORNAR unitResp?
            return [SELECT Status__c FROM Unit_Response__c WHERE Id =: unitId].Status__c == 'Completed' ? true : false;

        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }

    }
}